### ISSUE TITLE
Missing Spark JDBC Driver

### ISSUE THREAD

**Issue by jhajagos** [OHDSI/Broadsea-WebTools#13]
The War file for the latest release https://github.com/OHDSI/WebAPI/releases/tag/v2.11.1 does not appear to have the SPARK driver packaged:

```bash
docker exec -it broadsea-webtools_broadsea-webtools_1 /bin/bash
cd /usr/local/tomcat/webapps/WebAPI/WEB-INF/lib/
ls *spark*
```

The last result does not return any results.  I can see other JDBC Drivers in this directory including postgres, redshift.

**Comment by leeevans** [comment]
In general the drivers packaged in the War file are dependent on the WebAPI pom file and the maven profile used to build it. The spark driver is referenced in the webapi-spark profile in https://github.com/OHDSI/WebAPI/blob/master/pom.xml

In order to keep the Broadsea-Webtools container size manageable the preferred approach is to download a proprietary   jdbc driver (e.g. Spark) to the same directory as the docker-compose file and it will automatically be loaded when the container starts up.

See more details here:
https://github.com/OHDSI/Broadsea#deploy-proprietary-database-drivers
