### ISSUE TITLE
Supervisord

### ISSUE THREAD

**Issue by keyvaann** [OHDSI/Broadsea-WebTools#2]
Hi, I was wondering why Supervisord is used inside Docker image for WebTools? It would be useful if it was managing more than one service but in this case, I don't know its role in running the container.

**Comment by scivm** [comment]
Would you accept a pull request to remove supervisor?  I am thinking the image is more useful to run in kubernetes without supervisor.

**Comment by leeevans** [comment]
supervisord is there for two reasons:

1) It's a holdover from when this container launched others apps like Penelope, AchillesWeb - this reason is now void because we are only running a single Atlas/WebAPI app.
 
2) It was the (very) old way to catch signals and deal with pid 1 for docker containers.

I'd be happy to review a pull request where you remove supervisord and update the docker-compose file with the bold updates (version and init) below:

(FYI "https://docs.docker.com/compose/compose-file/#init" )

**version: "3.7"**
services:
  web:
    image: alpine:latest
    **init: true**

**Comment by keyvaann** [comment]
This could also be related to OHDSI/WebAPI#1384

**Comment by scivm** [comment]
I did send a pull request to start conversion.
